spring:
  datasource:
    url: jdbc:mysql://mysqlsunucu.mysql.database.azure.com:3306/localedige
    username: edige
    password: Melih.1854
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
openai:
  key: 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
server:
  port: 9090
